sudo: false
language: python
python:
  - "2.7"
  - "3.8"
  - "3.9"
install:
  - pip install python-coveralls
  - pip install pytest-mock
  - python setup.py install
script:
  - coverage run --source boardgamegeek --omit boardgamegeek/main.py -m py.test
after_success:
  - coveralls
